---
title: "Statistics Experience: TidyTuesday 4/8/25"
author: "Garrett Spooner"
date: "2025-04-07"
format: pdf
editor: visual
---

```{r}
library(tidyverse)
library(dplyr)


care_state <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-04-08/care_state.csv')
```

```{r}
filtered_data <- care_state |>
  filter(measure_id == "OP_18c") |>
  select(state, measure_name, score)
```

```{r}
library(dplyr)
library(ggplot2)
library(maps)
library(patchwork)
```

```{r}
filtered_data <- filtered_data |>
  mutate(state = tolower(state.name[match(state, state.abb)])) |>
  filter(!is.na(state))
```

```{r}
states_map <- map_data("state")

northeast_states <- c("connecticut", "maine", "massachusetts", "new hampshire",
                      "rhode island", "vermont", "new jersey", "new york", "pennsylvania")

southeast_states <- c("delaware", "florida", "georgia", "maryland", "north carolina", 
                      "south carolina", "virginia", "west virginia", "kentucky", 
                      "tennessee", "alabama", "mississippi", "arkansas", "louisiana")

map_data_joined <- states_map |>
  left_join(filtered_data, by = c("region" = "state"))
```

```{r}
northeast_map <- map_data_joined |>
  filter(region %in% northeast_states)

shared_limits <- c(175, 450)

NE <- ggplot(northeast_map, aes(long, lat, group = group, fill = score)) +
  geom_polygon(color = "white") +
  coord_fixed(1.3) +
  scale_fill_viridis_c(option = "C", limits = shared_limits) +
  labs(title = "Northeast US: ER Efficiency by State", fill = "ER score") +
  theme_void()

southeast_map <- map_data_joined %>%
  filter(region %in% southeast_states)

SE <- ggplot(southeast_map, aes(long, lat, group = group, fill = score)) +
  geom_polygon(color = "white") +
  coord_fixed(1.3) +
  scale_fill_viridis_c(option = "C", limits = shared_limits) +
  labs(title = "Southeast US: ER Efficiency by State", fill = "ER score") +
  theme_void()

NE + SE

#Used ChatGPT to understand maps package
```
